local connection = game.Destroying:Connect(function(arg)
end)
connection:Disconnect()
local connection2 = workspace.Destroying:Connect(function(arg2)
end)
connection2:Disconnect()
local Folder = Instance.new("Folder")
local connection3 = Folder.Destroying:Connect(function(arg3)
end)
connection3:Disconnect()
Folder:GetChildren()
Folder:Destroy()
local Folder2 = Instance.new("Folder", Folder)
local connection4 = Folder2.Destroying:Connect(function(arg4)
end)
connection4:Disconnect()
Folder2.Name = "940072265"
Folder:WaitForChild("940072265")
Folder:Destroy()
Folder2:Destroy()
local HttpService = game:GetService("HttpService")
local connection5 = HttpService.Destroying:Connect(function(arg5)
end)
connection5:Disconnect()
local RunService = game:GetService("RunService")
local connection6 = RunService.Destroying:Connect(function(arg6)
end)
connection6:Disconnect()
